/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.imsw.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.StagedGroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Borrower service. Represents a row in the &quot;BB_Borrower&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.imsw.model.impl.BorrowerModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.imsw.model.impl.BorrowerImpl}.
 * </p>
 *
 * @author User
 * @see Borrower
 * @see com.imsw.model.impl.BorrowerImpl
 * @see com.imsw.model.impl.BorrowerModelImpl
 * @generated
 */
public interface BorrowerModel extends BaseModel<Borrower>, StagedGroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a borrower model instance should use the {@link Borrower} interface instead.
	 */

	/**
	 * Returns the primary key of this borrower.
	 *
	 * @return the primary key of this borrower
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this borrower.
	 *
	 * @param primaryKey the primary key of this borrower
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this borrower.
	 *
	 * @return the uuid of this borrower
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this borrower.
	 *
	 * @param uuid the uuid of this borrower
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the borrower ID of this borrower.
	 *
	 * @return the borrower ID of this borrower
	 */
	public long getBorrowerId();

	/**
	 * Sets the borrower ID of this borrower.
	 *
	 * @param borrowerId the borrower ID of this borrower
	 */
	public void setBorrowerId(long borrowerId);

	/**
	 * Returns the group ID of this borrower.
	 *
	 * @return the group ID of this borrower
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this borrower.
	 *
	 * @param groupId the group ID of this borrower
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this borrower.
	 *
	 * @return the company ID of this borrower
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this borrower.
	 *
	 * @param companyId the company ID of this borrower
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this borrower.
	 *
	 * @return the user ID of this borrower
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this borrower.
	 *
	 * @param userId the user ID of this borrower
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this borrower.
	 *
	 * @return the user uuid of this borrower
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this borrower.
	 *
	 * @param userUuid the user uuid of this borrower
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this borrower.
	 *
	 * @return the user name of this borrower
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this borrower.
	 *
	 * @param userName the user name of this borrower
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this borrower.
	 *
	 * @return the create date of this borrower
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this borrower.
	 *
	 * @param createDate the create date of this borrower
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this borrower.
	 *
	 * @return the modified date of this borrower
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this borrower.
	 *
	 * @param modifiedDate the modified date of this borrower
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the name of this borrower.
	 *
	 * @return the name of this borrower
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this borrower.
	 *
	 * @param name the name of this borrower
	 */
	public void setName(String name);

	/**
	 * Returns the address of this borrower.
	 *
	 * @return the address of this borrower
	 */
	@AutoEscape
	public String getAddress();

	/**
	 * Sets the address of this borrower.
	 *
	 * @param address the address of this borrower
	 */
	public void setAddress(String address);

	/**
	 * Returns the city of this borrower.
	 *
	 * @return the city of this borrower
	 */
	@AutoEscape
	public String getCity();

	/**
	 * Sets the city of this borrower.
	 *
	 * @param city the city of this borrower
	 */
	public void setCity(String city);

	/**
	 * Returns the email of this borrower.
	 *
	 * @return the email of this borrower
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this borrower.
	 *
	 * @param email the email of this borrower
	 */
	public void setEmail(String email);

	/**
	 * Returns the phone no of this borrower.
	 *
	 * @return the phone no of this borrower
	 */
	@AutoEscape
	public String getPhoneNo();

	/**
	 * Sets the phone no of this borrower.
	 *
	 * @param PhoneNo the phone no of this borrower
	 */
	public void setPhoneNo(String PhoneNo);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.imsw.model.Borrower borrower);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.imsw.model.Borrower> toCacheModel();

	@Override
	public com.imsw.model.Borrower toEscapedModel();

	@Override
	public com.imsw.model.Borrower toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}