/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.imsw.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.StagedGroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Loan service. Represents a row in the &quot;BB_Loan&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.imsw.model.impl.LoanModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.imsw.model.impl.LoanImpl}.
 * </p>
 *
 * @author User
 * @see Loan
 * @see com.imsw.model.impl.LoanImpl
 * @see com.imsw.model.impl.LoanModelImpl
 * @generated
 */
public interface LoanModel extends BaseModel<Loan>, StagedGroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a loan model instance should use the {@link Loan} interface instead.
	 */

	/**
	 * Returns the primary key of this loan.
	 *
	 * @return the primary key of this loan
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this loan.
	 *
	 * @param primaryKey the primary key of this loan
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this loan.
	 *
	 * @return the uuid of this loan
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this loan.
	 *
	 * @param uuid the uuid of this loan
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the loan ID of this loan.
	 *
	 * @return the loan ID of this loan
	 */
	public long getLoanId();

	/**
	 * Sets the loan ID of this loan.
	 *
	 * @param loanId the loan ID of this loan
	 */
	public void setLoanId(long loanId);

	/**
	 * Returns the group ID of this loan.
	 *
	 * @return the group ID of this loan
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this loan.
	 *
	 * @param groupId the group ID of this loan
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this loan.
	 *
	 * @return the company ID of this loan
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this loan.
	 *
	 * @param companyId the company ID of this loan
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this loan.
	 *
	 * @return the user ID of this loan
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this loan.
	 *
	 * @param userId the user ID of this loan
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this loan.
	 *
	 * @return the user uuid of this loan
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this loan.
	 *
	 * @param userUuid the user uuid of this loan
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this loan.
	 *
	 * @return the user name of this loan
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this loan.
	 *
	 * @param userName the user name of this loan
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this loan.
	 *
	 * @return the create date of this loan
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this loan.
	 *
	 * @param createDate the create date of this loan
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this loan.
	 *
	 * @return the modified date of this loan
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this loan.
	 *
	 * @param modifiedDate the modified date of this loan
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the date start of this loan.
	 *
	 * @return the date start of this loan
	 */
	public Date getDateStart();

	/**
	 * Sets the date start of this loan.
	 *
	 * @param dateStart the date start of this loan
	 */
	public void setDateStart(Date dateStart);

	/**
	 * Returns the date finish of this loan.
	 *
	 * @return the date finish of this loan
	 */
	public Date getDateFinish();

	/**
	 * Sets the date finish of this loan.
	 *
	 * @param dateFinish the date finish of this loan
	 */
	public void setDateFinish(Date dateFinish);

	/**
	 * Returns the borrower ID of this loan.
	 *
	 * @return the borrower ID of this loan
	 */
	public long getBorrowerId();

	/**
	 * Sets the borrower ID of this loan.
	 *
	 * @param borrowerId the borrower ID of this loan
	 */
	public void setBorrowerId(long borrowerId);

	/**
	 * Returns the book ID of this loan.
	 *
	 * @return the book ID of this loan
	 */
	public long getBookId();

	/**
	 * Sets the book ID of this loan.
	 *
	 * @param bookId the book ID of this loan
	 */
	public void setBookId(long bookId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.imsw.model.Loan loan);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.imsw.model.Loan> toCacheModel();

	@Override
	public com.imsw.model.Loan toEscapedModel();

	@Override
	public com.imsw.model.Loan toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}