/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.docs.guestbook.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.StagedGroupedModel;
import com.liferay.portal.model.WorkflowedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the GuestBook service. Represents a row in the &quot;GB_GuestBook&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.docs.guestbook.model.impl.GuestBookModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.docs.guestbook.model.impl.GuestBookImpl}.
 * </p>
 *
 * @author User
 * @see GuestBook
 * @see com.liferay.docs.guestbook.model.impl.GuestBookImpl
 * @see com.liferay.docs.guestbook.model.impl.GuestBookModelImpl
 * @generated
 */
public interface GuestBookModel extends BaseModel<GuestBook>, StagedGroupedModel,
	WorkflowedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a guest book model instance should use the {@link GuestBook} interface instead.
	 */

	/**
	 * Returns the primary key of this guest book.
	 *
	 * @return the primary key of this guest book
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this guest book.
	 *
	 * @param primaryKey the primary key of this guest book
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this guest book.
	 *
	 * @return the uuid of this guest book
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this guest book.
	 *
	 * @param uuid the uuid of this guest book
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the guest book ID of this guest book.
	 *
	 * @return the guest book ID of this guest book
	 */
	public long getGuestBookId();

	/**
	 * Sets the guest book ID of this guest book.
	 *
	 * @param guestBookId the guest book ID of this guest book
	 */
	public void setGuestBookId(long guestBookId);

	/**
	 * Returns the group ID of this guest book.
	 *
	 * @return the group ID of this guest book
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this guest book.
	 *
	 * @param groupId the group ID of this guest book
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this guest book.
	 *
	 * @return the company ID of this guest book
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this guest book.
	 *
	 * @param companyId the company ID of this guest book
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this guest book.
	 *
	 * @return the user ID of this guest book
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this guest book.
	 *
	 * @param userId the user ID of this guest book
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this guest book.
	 *
	 * @return the user uuid of this guest book
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this guest book.
	 *
	 * @param userUuid the user uuid of this guest book
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this guest book.
	 *
	 * @return the user name of this guest book
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this guest book.
	 *
	 * @param userName the user name of this guest book
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this guest book.
	 *
	 * @return the create date of this guest book
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this guest book.
	 *
	 * @param createDate the create date of this guest book
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this guest book.
	 *
	 * @return the modified date of this guest book
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this guest book.
	 *
	 * @param modifiedDate the modified date of this guest book
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the name of this guest book.
	 *
	 * @return the name of this guest book
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this guest book.
	 *
	 * @param name the name of this guest book
	 */
	public void setName(String name);

	/**
	 * Returns the status of this guest book.
	 *
	 * @return the status of this guest book
	 */
	@Override
	public int getStatus();

	/**
	 * Sets the status of this guest book.
	 *
	 * @param status the status of this guest book
	 */
	@Override
	public void setStatus(int status);

	/**
	 * Returns the status by user ID of this guest book.
	 *
	 * @return the status by user ID of this guest book
	 */
	@Override
	public long getStatusByUserId();

	/**
	 * Sets the status by user ID of this guest book.
	 *
	 * @param statusByUserId the status by user ID of this guest book
	 */
	@Override
	public void setStatusByUserId(long statusByUserId);

	/**
	 * Returns the status by user uuid of this guest book.
	 *
	 * @return the status by user uuid of this guest book
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getStatusByUserUuid() throws SystemException;

	/**
	 * Sets the status by user uuid of this guest book.
	 *
	 * @param statusByUserUuid the status by user uuid of this guest book
	 */
	@Override
	public void setStatusByUserUuid(String statusByUserUuid);

	/**
	 * Returns the status by user name of this guest book.
	 *
	 * @return the status by user name of this guest book
	 */
	@AutoEscape
	@Override
	public String getStatusByUserName();

	/**
	 * Sets the status by user name of this guest book.
	 *
	 * @param statusByUserName the status by user name of this guest book
	 */
	@Override
	public void setStatusByUserName(String statusByUserName);

	/**
	 * Returns the status date of this guest book.
	 *
	 * @return the status date of this guest book
	 */
	@Override
	public Date getStatusDate();

	/**
	 * Sets the status date of this guest book.
	 *
	 * @param statusDate the status date of this guest book
	 */
	@Override
	public void setStatusDate(Date statusDate);

	/**
	 * @deprecated As of 6.1.0, replaced by {@link #isApproved()}
	 */
	@Override
	public boolean getApproved();

	/**
	 * Returns <code>true</code> if this guest book is approved.
	 *
	 * @return <code>true</code> if this guest book is approved; <code>false</code> otherwise
	 */
	@Override
	public boolean isApproved();

	/**
	 * Returns <code>true</code> if this guest book is denied.
	 *
	 * @return <code>true</code> if this guest book is denied; <code>false</code> otherwise
	 */
	@Override
	public boolean isDenied();

	/**
	 * Returns <code>true</code> if this guest book is a draft.
	 *
	 * @return <code>true</code> if this guest book is a draft; <code>false</code> otherwise
	 */
	@Override
	public boolean isDraft();

	/**
	 * Returns <code>true</code> if this guest book is expired.
	 *
	 * @return <code>true</code> if this guest book is expired; <code>false</code> otherwise
	 */
	@Override
	public boolean isExpired();

	/**
	 * Returns <code>true</code> if this guest book is inactive.
	 *
	 * @return <code>true</code> if this guest book is inactive; <code>false</code> otherwise
	 */
	@Override
	public boolean isInactive();

	/**
	 * Returns <code>true</code> if this guest book is incomplete.
	 *
	 * @return <code>true</code> if this guest book is incomplete; <code>false</code> otherwise
	 */
	@Override
	public boolean isIncomplete();

	/**
	 * Returns <code>true</code> if this guest book is pending.
	 *
	 * @return <code>true</code> if this guest book is pending; <code>false</code> otherwise
	 */
	@Override
	public boolean isPending();

	/**
	 * Returns <code>true</code> if this guest book is scheduled.
	 *
	 * @return <code>true</code> if this guest book is scheduled; <code>false</code> otherwise
	 */
	@Override
	public boolean isScheduled();

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.liferay.docs.guestbook.model.GuestBook guestBook);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.liferay.docs.guestbook.model.GuestBook> toCacheModel();

	@Override
	public com.liferay.docs.guestbook.model.GuestBook toEscapedModel();

	@Override
	public com.liferay.docs.guestbook.model.GuestBook toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}