/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.imsw.model.impl;

import com.imsw.model.Loan;
import com.imsw.model.LoanModel;
import com.imsw.model.LoanSoap;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.lar.StagedModelType;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the Loan service. Represents a row in the &quot;BB_Loan&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.imsw.model.LoanModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link LoanImpl}.
 * </p>
 *
 * @author User
 * @see LoanImpl
 * @see com.imsw.model.Loan
 * @see com.imsw.model.LoanModel
 * @generated
 */
@JSON(strict = true)
public class LoanModelImpl extends BaseModelImpl<Loan> implements LoanModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a loan model instance should use the {@link com.imsw.model.Loan} interface instead.
	 */
	public static final String TABLE_NAME = "BB_Loan";
	public static final Object[][] TABLE_COLUMNS = {
			{ "uuid_", Types.VARCHAR },
			{ "loanId", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "userName", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "dateStart", Types.TIMESTAMP },
			{ "dateFinish", Types.TIMESTAMP },
			{ "borrowerId", Types.BIGINT },
			{ "bookId", Types.BIGINT }
		};
	public static final String TABLE_SQL_CREATE = "create table BB_Loan (uuid_ VARCHAR(75) null,loanId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,dateStart DATE null,dateFinish DATE null,borrowerId LONG,bookId LONG)";
	public static final String TABLE_SQL_DROP = "drop table BB_Loan";
	public static final String ORDER_BY_JPQL = " ORDER BY loan.loanId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY BB_Loan.loanId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.imsw.model.Loan"), true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.imsw.model.Loan"), true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.imsw.model.Loan"), true);
	public static long BOOKID_COLUMN_BITMASK = 1L;
	public static long BORROWERID_COLUMN_BITMASK = 2L;
	public static long COMPANYID_COLUMN_BITMASK = 4L;
	public static long GROUPID_COLUMN_BITMASK = 8L;
	public static long UUID_COLUMN_BITMASK = 16L;
	public static long LOANID_COLUMN_BITMASK = 32L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static Loan toModel(LoanSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		Loan model = new LoanImpl();

		model.setUuid(soapModel.getUuid());
		model.setLoanId(soapModel.getLoanId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setDateStart(soapModel.getDateStart());
		model.setDateFinish(soapModel.getDateFinish());
		model.setBorrowerId(soapModel.getBorrowerId());
		model.setBookId(soapModel.getBookId());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<Loan> toModels(LoanSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<Loan> models = new ArrayList<Loan>(soapModels.length);

		for (LoanSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.imsw.model.Loan"));

	public LoanModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _loanId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setLoanId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _loanId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Loan.class;
	}

	@Override
	public String getModelClassName() {
		return Loan.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("uuid", getUuid());
		attributes.put("loanId", getLoanId());
		attributes.put("groupId", getGroupId());
		attributes.put("companyId", getCompanyId());
		attributes.put("userId", getUserId());
		attributes.put("userName", getUserName());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("dateStart", getDateStart());
		attributes.put("dateFinish", getDateFinish());
		attributes.put("borrowerId", getBorrowerId());
		attributes.put("bookId", getBookId());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		String uuid = (String)attributes.get("uuid");

		if (uuid != null) {
			setUuid(uuid);
		}

		Long loanId = (Long)attributes.get("loanId");

		if (loanId != null) {
			setLoanId(loanId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		Date dateStart = (Date)attributes.get("dateStart");

		if (dateStart != null) {
			setDateStart(dateStart);
		}

		Date dateFinish = (Date)attributes.get("dateFinish");

		if (dateFinish != null) {
			setDateFinish(dateFinish);
		}

		Long borrowerId = (Long)attributes.get("borrowerId");

		if (borrowerId != null) {
			setBorrowerId(borrowerId);
		}

		Long bookId = (Long)attributes.get("bookId");

		if (bookId != null) {
			setBookId(bookId);
		}
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return StringPool.BLANK;
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@JSON
	@Override
	public long getLoanId() {
		return _loanId;
	}

	@Override
	public void setLoanId(long loanId) {
		_loanId = loanId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	@Override
	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return StringPool.BLANK;
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public Date getDateStart() {
		return _dateStart;
	}

	@Override
	public void setDateStart(Date dateStart) {
		_dateStart = dateStart;
	}

	@JSON
	@Override
	public Date getDateFinish() {
		return _dateFinish;
	}

	@Override
	public void setDateFinish(Date dateFinish) {
		_dateFinish = dateFinish;
	}

	@JSON
	@Override
	public long getBorrowerId() {
		return _borrowerId;
	}

	@Override
	public void setBorrowerId(long borrowerId) {
		_columnBitmask |= BORROWERID_COLUMN_BITMASK;

		if (!_setOriginalBorrowerId) {
			_setOriginalBorrowerId = true;

			_originalBorrowerId = _borrowerId;
		}

		_borrowerId = borrowerId;
	}

	public long getOriginalBorrowerId() {
		return _originalBorrowerId;
	}

	@JSON
	@Override
	public long getBookId() {
		return _bookId;
	}

	@Override
	public void setBookId(long bookId) {
		_columnBitmask |= BOOKID_COLUMN_BITMASK;

		if (!_setOriginalBookId) {
			_setOriginalBookId = true;

			_originalBookId = _bookId;
		}

		_bookId = bookId;
	}

	public long getOriginalBookId() {
		return _originalBookId;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(PortalUtil.getClassNameId(
				Loan.class.getName()));
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			Loan.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Loan toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (Loan)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		LoanImpl loanImpl = new LoanImpl();

		loanImpl.setUuid(getUuid());
		loanImpl.setLoanId(getLoanId());
		loanImpl.setGroupId(getGroupId());
		loanImpl.setCompanyId(getCompanyId());
		loanImpl.setUserId(getUserId());
		loanImpl.setUserName(getUserName());
		loanImpl.setCreateDate(getCreateDate());
		loanImpl.setModifiedDate(getModifiedDate());
		loanImpl.setDateStart(getDateStart());
		loanImpl.setDateFinish(getDateFinish());
		loanImpl.setBorrowerId(getBorrowerId());
		loanImpl.setBookId(getBookId());

		loanImpl.resetOriginalValues();

		return loanImpl;
	}

	@Override
	public int compareTo(Loan loan) {
		long primaryKey = loan.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof Loan)) {
			return false;
		}

		Loan loan = (Loan)obj;

		long primaryKey = loan.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		LoanModelImpl loanModelImpl = this;

		loanModelImpl._originalUuid = loanModelImpl._uuid;

		loanModelImpl._originalGroupId = loanModelImpl._groupId;

		loanModelImpl._setOriginalGroupId = false;

		loanModelImpl._originalCompanyId = loanModelImpl._companyId;

		loanModelImpl._setOriginalCompanyId = false;

		loanModelImpl._originalBorrowerId = loanModelImpl._borrowerId;

		loanModelImpl._setOriginalBorrowerId = false;

		loanModelImpl._originalBookId = loanModelImpl._bookId;

		loanModelImpl._setOriginalBookId = false;

		loanModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<Loan> toCacheModel() {
		LoanCacheModel loanCacheModel = new LoanCacheModel();

		loanCacheModel.uuid = getUuid();

		String uuid = loanCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			loanCacheModel.uuid = null;
		}

		loanCacheModel.loanId = getLoanId();

		loanCacheModel.groupId = getGroupId();

		loanCacheModel.companyId = getCompanyId();

		loanCacheModel.userId = getUserId();

		loanCacheModel.userName = getUserName();

		String userName = loanCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			loanCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			loanCacheModel.createDate = createDate.getTime();
		}
		else {
			loanCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			loanCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			loanCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		Date dateStart = getDateStart();

		if (dateStart != null) {
			loanCacheModel.dateStart = dateStart.getTime();
		}
		else {
			loanCacheModel.dateStart = Long.MIN_VALUE;
		}

		Date dateFinish = getDateFinish();

		if (dateFinish != null) {
			loanCacheModel.dateFinish = dateFinish.getTime();
		}
		else {
			loanCacheModel.dateFinish = Long.MIN_VALUE;
		}

		loanCacheModel.borrowerId = getBorrowerId();

		loanCacheModel.bookId = getBookId();

		return loanCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(25);

		sb.append("{uuid=");
		sb.append(getUuid());
		sb.append(", loanId=");
		sb.append(getLoanId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", dateStart=");
		sb.append(getDateStart());
		sb.append(", dateFinish=");
		sb.append(getDateFinish());
		sb.append(", borrowerId=");
		sb.append(getBorrowerId());
		sb.append(", bookId=");
		sb.append(getBookId());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(40);

		sb.append("<model><model-name>");
		sb.append("com.imsw.model.Loan");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>uuid</column-name><column-value><![CDATA[");
		sb.append(getUuid());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>loanId</column-name><column-value><![CDATA[");
		sb.append(getLoanId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>dateStart</column-name><column-value><![CDATA[");
		sb.append(getDateStart());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>dateFinish</column-name><column-value><![CDATA[");
		sb.append(getDateFinish());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>borrowerId</column-name><column-value><![CDATA[");
		sb.append(getBorrowerId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>bookId</column-name><column-value><![CDATA[");
		sb.append(getBookId());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = Loan.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] { Loan.class };
	private String _uuid;
	private String _originalUuid;
	private long _loanId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _userId;
	private String _userUuid;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private Date _dateStart;
	private Date _dateFinish;
	private long _borrowerId;
	private long _originalBorrowerId;
	private boolean _setOriginalBorrowerId;
	private long _bookId;
	private long _originalBookId;
	private boolean _setOriginalBookId;
	private long _columnBitmask;
	private Loan _escapedModel;
}